function initializeOptionPanel(h)
% INITIALIZEOPTIONPANEL initializes the Step 3 panel

% Author: Rong Chen 
%  Copyright 1986-2012 The MathWorks, Inc.


% -------------------------------------------------------------------------
%% Build timeseries naming option control and its contents
% -------------------------------------------------------------------------
h.DefaultPos.OptionPanelDefaultColor=h.DefaultPos.FigureDefaultColor;
h.Handles.PNLoption = uibuttongroup('Parent',h.Figure, ...
    'Units','Pixels', ...
    'BackgroundColor',h.DefaultPos.OptionPanelDefaultColor, ...
    'SelectionChangeFcn',{@localRadio,h}, ...
    'Position',[h.DefaultPos.leftoffsetDynamicPnl ...
                h.DefaultPos.buttomoffsetDynamicPnl ...
                h.DefaultPos.widthDynamicPnl ...
                h.DefaultPos.heightDynamicPnl], ...
    'Visible','off' ...
    );

huicRADIOsingleNEW = uicontextmenu('Parent',h.Figure);
strCreateNewTSwithName = getString(message('MATLAB:tsguis:ImportWizard:initializeOptionPanel:CreateNewTimeSeriesWithName'));
h.Handles.RADIOsingleNEW = uicontrol('Parent',h.Handles.PNLoption, ...
    'style','radiobutton',...
    'Units','Pixels', ...
    'BackgroundColor',h.DefaultPos.OptionPanelDefaultColor, ...
    'String',sprintf(' %s : ', strCreateNewTSwithName), ...
    'UIContextMenu',huicRADIOsingleNEW,...
    'Position',[h.DefaultPos.RADIOoptionleftoffset ...
                h.DefaultPos.RADIOoptionbottomoffset_singleNew ...
                h.DefaultPos.RADIOoptionwidth ...
                h.DefaultPos.heightradio], ...
    'tag', 'RADIOsingleNEW' ...                    
    );

strWhatsThis = getString(message('MATLAB:tsguis:ImportWizard:initializeOptionPanel:WhatsThis'));
uimenu(huicRADIOsingleNEW,'Label',strWhatsThis,'Callback','tsDispatchHelp(''its_wiz_create_one_ts'',''modal'')')

h.Handles.EDTsingleNEW = uicontrol('Parent',h.Handles.PNLoption, ...
    'style','edit', ...
    'Units','Pixels', ...
    'BackgroundColor',[1 1 1], ...
    'String','', ...
    'TooltipString',getString(message('MATLAB:tsguis:ImportWizard:initializeOptionPanel:EnterNameOfTimeSeriesObjectToBeImported')), ...
    'HorizontalAlignment','Left', ...
    'Position',[h.DefaultPos.EDToptionleftoffset ...
                h.DefaultPos.RADIOoptionbottomoffset_singleNew-2 ...
                h.DefaultPos.EDToptionwidth ...
                h.DefaultPos.heightedt], ...
    'tag', 'EDTsingleNEW' ...
    );

strCreateSeveralTimeSeries = getString(message('MATLAB:tsguis:ImportWizard:initializeOptionPanel:CreateSeveralTimeSeries'));
huicRADIOmultipleNEW = uicontextmenu('Parent',h.Figure);
h.Handles.RADIOmultipleNEW = uicontrol('Parent',h.Handles.PNLoption, ...
    'style','radiobutton',...
    'Units','Pixels', ...
    'BackgroundColor',h.DefaultPos.OptionPanelDefaultColor, ...
    'String',sprintf(' %s : ',strCreateSeveralTimeSeries), ...
    'UIContextMenu',huicRADIOmultipleNEW,...
    'Position',[h.DefaultPos.RADIOoptionleftoffset ...
                h.DefaultPos.RADIOoptionbottomoffset_multipleNew ...
                h.DefaultPos.RADIOoptionwidth ...
                h.DefaultPos.heightradio], ...
    'tag', 'RADIOmultipleNEW'...             
    );

uimenu(huicRADIOmultipleNEW,'Label',strWhatsThis,'Callback','tsDispatchHelp(''its_wiz_create_several_ts'',''modal'')')

h.Handles.COMBmultipleNEW = uicontrol('Parent',h.Handles.PNLoption, ...
    'style','popupmenu', ...
    'Units','Pixels', ...
    'String', {getString(message('MATLAB:tsguis:ImportWizard:initializeOptionPanel:NamesInDataSource')) getString(message('MATLAB:tsguis:ImportWizard:initializeOptionPanel:CommonNameAndNumber'))}, ...
    'Value',1, ...
    'TooltipString',getString(message('MATLAB:tsguis:ImportWizard:initializeOptionPanel:TimeseriesRowcolumnVariableNamesOption')), ...
    'Position',[h.DefaultPos.EDToptionleftoffset ...
                h.DefaultPos.RADIOoptionbottomoffset_multipleNew ...
                h.DefaultPos.EDToptionwidth ...
                h.DefaultPos.heighttxt], ...
    'Callback',{@localSwitchMultiple h}, ...
    'tag', 'COMBmultipleNEW'...
    );
if ~ismac
   set(h.Handles.COMBmultipleNEW,'BackgroundColor',[1 1 1]);
end

strVarSpecifyRow = getString(message('MATLAB:tsguis:ImportWizard:initializeOptionPanel:SpecifyRow'));
    huicTXTmultipleNEW = uicontextmenu('Parent',h.Figure);
h.Handles.TXTmultipleNEW = uicontrol('Parent',h.Handles.PNLoption, ...
    'style','text',...
    'Units','Pixels', ...
    'BackgroundColor',h.DefaultPos.OptionPanelDefaultColor, ...
    'String',sprintf(' %s : ',strVarSpecifyRow), ... %jgo
    'HorizontalAlignment','Left', ...
    'UIContextMenu',huicTXTmultipleNEW,...
    'Position',[h.DefaultPos.EDToptionleftoffset+h.DefaultPos.EDToptionwidth+h.DefaultPos.TXToptionmultipleleftoffset ...
                h.DefaultPos.RADIOoptionbottomoffset_multipleNew-4 ...
                h.DefaultPos.TXToptionmultiplewidth ...
                h.DefaultPos.heighttxt] ...
    );
uimenu(huicTXTmultipleNEW,'Label',strWhatsThis,'Callback','tsDispatchHelp(''its_wiz_name_ts_from_row'',''modal'')')

h.Handles.EDTmultipleNEW = uicontrol('Parent',h.Handles.PNLoption, ...
    'style','edit', ...
    'Units','Pixels', ...
    'BackgroundColor',[1 1 1], ...
    'String','', ...
    'TooltipString',getString(message('MATLAB:tsguis:ImportWizard:initializeOptionPanel:KeyInRowNumbercolumnLetterOrCommonPart')),...
    'HorizontalAlignment','Left', ...
    'Position',[h.DefaultPos.EDToptionleftoffset+...
                h.DefaultPos.EDToptionwidth+5+h.DefaultPos.TXToptionmultiplewidth+...%40jgo
                h.DefaultPos.separation ...
                h.DefaultPos.RADIOoptionbottomoffset_multipleNew-2 ...
                h.DefaultPos.EDToptionmultiplewidth ...
                h.DefaultPos.heightedt], ...
    'tag', 'EDTmultipleNEW'...            
    );

strAppendDataToAnExistingTimeSeries = getString(message('MATLAB:tsguis:ImportWizard:initializeOptionPanel:AppendDataToAnExistingTimeSeries'));
huicRADIOsingleINSERT = uicontextmenu('Parent',h.Figure);
h.Handles.RADIOsingleINSERT = uicontrol('Parent',h.Handles.PNLoption, ...
    'style','radiobutton',...
    'Units','Pixels', ...
    'BackgroundColor',h.DefaultPos.OptionPanelDefaultColor, ...
    'String',sprintf(' %s : ',strAppendDataToAnExistingTimeSeries), ...
    'UIContextMenu',huicRADIOsingleINSERT,...
    'Position',[h.DefaultPos.RADIOoptionleftoffset ...
                h.DefaultPos.RADIOoptionbottomoffset_singleINSERT ...
                h.DefaultPos.RADIOoptionwidth ...
                h.DefaultPos.heightradio], ...
    'tag', 'RADIOsingleINSERT' ...
    );
uimenu(huicRADIOsingleINSERT,'Label',strWhatsThis,'Callback','tsDispatchHelp(''its_wiz_append_data_to_ts'',''modal'')')

h.Handles.COMBsingleINSERT = uicontrol('Parent',h.Handles.PNLoption, ...
    'style','popupmenu', ...
    'Units','Pixels', ...
    'String',{''},...
    'TooltipString',getString(message('MATLAB:tsguis:ImportWizard:initializeOptionPanel:SelectTimeSeriesObjectFromList')),...
    'Position',[h.DefaultPos.EDToptionleftoffset ...
                h.DefaultPos.RADIOoptionbottomoffset_singleINSERT ...
                h.DefaultPos.EDToptionwidth ...
                h.DefaultPos.heighttxt] ...
);
if ~ismac
   set(h.Handles.COMBsingleINSERT,'BackgroundColor',[1 1 1]);
end
    
%populate combobox with current timeseries objects in the base workspace
localRefresh([], [], h);
huicBTNRefresh = uicontextmenu('Parent',h.Figure);
h.Handles.BTNRefresh = uicontrol('Parent',h.Handles.PNLoption, ...
    'style','pushbutton', ...
    'Units','Pixels', ...
    'String',getString(message('MATLAB:tsguis:ImportWizard:initializeOptionPanel:RefreshList')),...
    'UIContextMenu',huicBTNRefresh,...
    'Position',[h.DefaultPos.EDToptionleftoffset+h.DefaultPos.EDToptionwidth+h.DefaultPos.TXToptionmultipleleftoffset ...
                h.DefaultPos.RADIOoptionbottomoffset_singleINSERT-5 ...
                120 ...
                h.DefaultPos.heightbtn], ...
    'Callback',{@localRefresh h}, ...
    'Tag', 'BTNrefresh');
uimenu(huicBTNRefresh,'Label',strWhatsThis,'Callback','tsDispatchHelp(''its_wiz_refresh_ts_list'',''modal'')')

% initialize radiobuttons
set(h.Handles.PNLoption,'SelectedObject',h.Handles.RADIOsingleNEW);
set(h.Handles.COMBmultipleNEW,'Enable','off');
set(h.Handles.EDTmultipleNEW,'Enable','off','BackgroundColor',h.DefaultPos.OptionPanelDefaultColor);
set(h.Handles.COMBsingleINSERT,'Enable','off');
set(h.Handles.BTNRefresh,'Enable','off');


function localRefresh(eventSrc, eventData, h)
tsgui=tsguis.tsviewer;
all_childnodes = tsgui.Tsnode.getChildren;
alltsobjects={};
for i=1:length(all_childnodes)
    if isa(all_childnodes(i),'tsguis.tsnode')
        alltsobjects{end+1} = all_childnodes(i).Timeseries;
    end
end
strCell={};
for i=1:length(alltsobjects)
    strCell=[strCell {alltsobjects{i}.Name}];
end
if isempty(strCell)
    strCell={''};
end
set(h.Handles.COMBsingleINSERT,'String', strCell,'Value',1);


function localRadio(eventSrc, eventData, h)
% callback for the radiobutton group
if get(eventSrc,'SelectedObject')==h.Handles.RADIOsingleNEW
    % single new
    set(h.Handles.EDTsingleNEW,'Enable','on','BackgroundColor',[1 1 1]);
    set(h.Handles.COMBmultipleNEW,'Enable','off');
    set(h.Handles.EDTmultipleNEW,'Enable','off','BackgroundColor',h.DefaultPos.OptionPanelDefaultColor);
    set(h.Handles.COMBsingleINSERT,'Enable','off');
    set(h.Handles.BTNRefresh,'Enable','off');
elseif get(eventSrc,'SelectedObject')==h.Handles.RADIOmultipleNEW
    set(h.Handles.EDTsingleNEW,'Enable','off','BackgroundColor',h.DefaultPos.OptionPanelDefaultColor);
    set(h.Handles.COMBmultipleNEW,'Enable','on');
    set(h.Handles.EDTmultipleNEW,'Enable','on','BackgroundColor',[1 1 1]);
    set(h.Handles.COMBsingleINSERT,'Enable','off');
    set(h.Handles.BTNRefresh,'Enable','off');
else
    set(h.Handles.EDTsingleNEW,'Enable','off','BackgroundColor',h.DefaultPos.OptionPanelDefaultColor);
    set(h.Handles.COMBmultipleNEW,'Enable','off');
    set(h.Handles.EDTmultipleNEW,'Enable','off','BackgroundColor',h.DefaultPos.OptionPanelDefaultColor);
    set(h.Handles.COMBsingleINSERT,'Enable','on');
    set(h.Handles.BTNRefresh,'Enable','on');
end


function localSwitchMultiple(eventSrc, eventData, h)

source = get(h.Handles.COMBsource,'Value');
if get(h.Handles.COMBmultipleNEW,'Value')==1
    % use a row or column as name
    strVarWhatsThis = getString(message('MATLAB:tsguis:ImportWizard:initializeOptionPanel:WhatsThis'));
    strSpecifyRow = getString(message('MATLAB:tsguis:ImportWizard:initializeOptionPanel:SpecifyRow'));
    strSpecifyColumn = getString(message('MATLAB:tsguis:ImportWizard:initializeOptionPanel:SpecifyColumn'));

    if source==1
        % excel
        if get(h.Handles.exceldlg.Handles.COMBdataSample,'Value')==1
            % a sample is a row
            huicTXTmultipleNEW = uicontextmenu('Parent',h.Figure);
            uimenu(huicTXTmultipleNEW,'Label',strVarWhatsThis,'Callback','tsDispatchHelp(''its_wiz_name_ts_from_row'',''modal'')')
            set(h.Handles.TXTmultipleNEW,'String',sprintf('%s : ',strSpecifyRow),'UIContextMenu',huicTXTmultipleNEW);
            set(h.Handles.EDTmultipleNEW,'String','1');
        else
            huicTXTmultipleNEW = uicontextmenu('Parent',h.Figure);
            uimenu(huicTXTmultipleNEW,'Label',strVarWhatsThis,'Callback','tsDispatchHelp(''its_wiz_name_ts_from_column_xls'',''modal'')')
            set(h.Handles.TXTmultipleNEW,'String',sprintf('%s : ',strSpecifyColumn),'UIContextMenu',huicTXTmultipleNEW);
            set(h.Handles.EDTmultipleNEW,'String','A');
        end
    elseif source==2
        % text
        if get(h.Handles.csvdlg.Handles.COMBdataSample,'Value')==1
            % a sample is a row
            huicTXTmultipleNEW = uicontextmenu('Parent',h.Figure);
            uimenu(huicTXTmultipleNEW,'Label',strVarWhatsThis,'Callback','tsDispatchHelp(''its_wiz_name_ts_from_row'',''modal'')')
            set(h.Handles.TXTmultipleNEW,'String',sprintf('%s : ',strSpecifyRow),'UIContextMenu',huicTXTmultipleNEW);
            set(h.Handles.EDTmultipleNEW,'String','1');
        else
            huicTXTmultipleNEW = uicontextmenu('Parent',h.Figure);
            uimenu(huicTXTmultipleNEW,'Label',strVarWhatsThis,'Callback','tsDispatchHelp(''its_wiz_name_ts_from_column_xls'',''modal'')')
            set(h.Handles.TXTmultipleNEW,'String',sprintf('%s : ',strSpecifyColumn),'UIContextMenu',huicTXTmultipleNEW);
            set(h.Handles.EDTmultipleNEW,'String','A');
        end
    elseif source==3
        % mat
        if get(h.Handles.matdlg.Handles.COMBdataSample,'Value')==1
            % a sample is a row
            huicTXTmultipleNEW = uicontextmenu('Parent',h.Figure);
            uimenu(huicTXTmultipleNEW,'Label',strVarWhatsThis,'Callback','tsDispatchHelp(''its_wiz_name_ts_from_row'',''modal'')')
            set(h.Handles.TXTmultipleNEW,'String',sprintf('%s : ',strSpecifyRow),'UIContextMenu',huicTXTmultipleNEW);
            set(h.Handles.EDTmultipleNEW,'String','1');
        else
            huicTXTmultipleNEW = uicontextmenu('Parent',h.Figure);
            uimenu(huicTXTmultipleNEW,'Label',strVarWhatsThis,'Callback','tsDispatchHelp(''its_wiz_name_ts_from_column_mat'',''modal'')')
            set(h.Handles.TXTmultipleNEW,'String',sprintf('%s : ',strSpecifyColumn),'UIContextMenu',huicTXTmultipleNEW);
            set(h.Handles.EDTmultipleNEW,'String','1');
        end
    elseif source==4
        % workspace
        if get(h.Handles.workspacedlg.Handles.COMBdataSample,'Value')==1
            % a sample is a row
            huicTXTmultipleNEW = uicontextmenu('Parent',h.Figure);
            uimenu(huicTXTmultipleNEW,'Label',strVarWhatsThis,'Callback','tsDispatchHelp(''its_wiz_name_ts_from_row'',''modal'')')
            set(h.Handles.TXTmultipleNEW,'String',sprintf('%s : ',strSpecifyRow),'UIContextMenu',huicTXTmultipleNEW);
            set(h.Handles.EDTmultipleNEW,'String','1');
        else
            huicTXTmultipleNEW = uicontextmenu('Parent',h.Figure);
            uimenu(huicTXTmultipleNEW,'Label',strVarWhatsThis,'Callback','tsDispatchHelp(''its_wiz_name_ts_from_column_mat'',''modal'')')
            set(h.Handles.TXTmultipleNEW,'String',sprintf('%s : ',strSpecifyColumn),'UIContextMenu',huicTXTmultipleNEW);
            set(h.Handles.EDTmultipleNEW,'String','1');
        end
    end
else
    huicTXTmultipleNEW = uicontextmenu('Parent',h.Figure);
    strVariableWhatsThis = getString(message('MATLAB:tsguis:ImportWizard:initializeOptionPanel:WhatsThis'));
    strVarCommonName = getString(message('MATLAB:tsguis:ImportWizard:initializeOptionPanel:CommonName'));
    
    uimenu(huicTXTmultipleNEW,'Label',strVariableWhatsThis,'Callback','tsDispatchHelp(''its_wiz_common_name'',''modal'')')
    set(h.Handles.TXTmultipleNEW,'String',sprintf('%s : ',strVarCommonName),'UIContextMenu',huicTXTmultipleNEW);
    if source==1
        % excel
        strCell=get(h.Handles.COMBdataSheet,'String');
        set(h.Handles.EDTmultipleNEW,'String',strCell{get(h.Handles.COMBdataSheet,'Value')});
    elseif source==3
        % mat
        set(h.Handles.EDTmultipleNEW,'String',h.Handles.matdlg.IOData.SelectedVariableInfo.varname);
    elseif source==4
        % workspace
        set(h.Handles.EDTmultipleNEW,'String',h.Handles.workspacedlg.IOData.SelectedVariableInfo.varname);
    end
end