function initialize(h)

% Copyright 2004-2012 The MathWorks, Inc.

%% Builds the Data Selection GUI

import javax.swing.*; 
import com.mathworks.mwswing.*;
import com.mathworks.toolbox.timeseries.*;

% Build buttons
h.Handles.BTNok = uicontrol('String', ...
    getString(message('MATLAB:timeseries:tsguis:mergedlg:OK')), ...
    'Parent',h.Figure,'Units','Characters','Position',...
    [53.6-15 1.1535 13.8 1.7687],'Callback',{@localOK h},'BusyAction', 'Cancel',...
    'Interruptible','off','Tag','BTNok');
h.Handles.BTNcancel = uicontrol('String', ...
    getString(message('MATLAB:timeseries:tsguis:mergedlg:Cancel')), ...
    'Parent',h.Figure,'Units','Characters','Position',...
    [70-15.5 1.1535 13.8 1.7687],'Callback',{@localClose h},'Tag','BTNcancel');
h.Handles.BTNhelp = uicontrol('String', ...
    getString(message('MATLAB:timeseries:tsguis:mergedlg:Help')), ...
    'Parent',h.Figure,'Units','Characters','Position',...
    [70 1.1535 13.8 1.7687],'Callback',{@localDispatchhelp h});

% Build time series panel
PNLselectTs = uibuttongroup('Parent',h.Figure,'Units','Characters','Position', ...
    [2.2 21.7627 80.8 15],'Title', getString(message('MATLAB:timeseries:tsguis:mergedlg:DefineTimeSeries')));
h.Handles.tsTableModel = tsMatlabCallbackTableModel(cell(0,4),...
             {getString(message('MATLAB:timeseries:tsguis:mergedlg:Modifyyn')), ...
             getString(message('MATLAB:timeseries:tsguis:mergedlg:TimeSeries')), ...
             getString(message('MATLAB:timeseries:tsguis:mergedlg:Path'))}, ...
             'tsDispatchTableCallback',...
             {'refresh' 1 h});
drawnow
h.Handles.tsTableModel.setNoEditCols([1 2]);        
h.Handles.tsTable = javaObjectEDT('com.mathworks.mwswing.MJTable',h.Handles.tsTableModel);
h.Handles.tsTable.setName('mergedlg:tstable');
javaMethod('setPreferredWidth',h.Handles.tsTable.getColumnModel.getColumn(2),...
    200);
javaMethod('setAutoResizeMode',h.Handles.tsTable,JTable.AUTO_RESIZE_OFF);
sPanel = javaObjectEDT('com.mathworks.mwswing.MJScrollPane',h.Handles.tsTable);
[~,tsTablePanel] = javacomponent(sPanel,[0 0 1 1],h.Figure);
c = javaObjectEDT('javax.swing.JCheckBox');
javaMethod('setCellEditor',h.Handles.tsTable.getColumnModel.getColumn(0),...
    DefaultCellEditor(c));
javaMethod('setCellRenderer',h.Handles.tsTable.getColumnModel.getColumn(0),...
    tsCheckBoxRenderer);
set(tsTablePanel,'Units','Pixels','Parent',PNLselectTs,'Position', ...
    hgconvertunits(ancestor(PNLselectTs,'figure'),[3.2 5.5368 74.4 7.6900],...
    'Characters','Pixels',PNLselectTs))
h.Handles.RADIOinplace = uicontrol('style','radiobutton','String',...
    getString(message('MATLAB:timeseries:tsguis:mergedlg:OverwriteSelectedTimeSeries')), ...
    'Units',...
    'Characters','Parent',PNLselectTs,'Position',[3.8 3.2298 40.8 1.1535],...
    'Tag', 'RADIOinplace', 'Value',1);
h.Handles.RADIOnewmerged = uicontrol('style','radiobutton','String',...
    getString(message('MATLAB:timeseries:tsguis:mergedlg:CreateNewTimeSeries')),'Units',...
    'Characters','Parent',PNLselectTs,'Position',[3.8 1.4611 52.8 1.1535],...
    'Tag', 'RADIOnewmerged');

% 1st column is HTML
h.ViewNode.getRoot.setHTMTableColumn(h.Handles.tsTable,2);

% Build time interval panel
PNLInterval = uibuttongroup('Parent',h.Figure,'Units','Characters','Position', ...
    [2.2 9.6894 81.6 11.5350],'Title',getString(message('MATLAB:timeseries:tsguis:mergedlg:SpecifyNewTimeVector')),'SelectionChangeFcn',...
    {@localRefresh h});
h.Handles.RADIOunion = uicontrol('style','radiobutton','String',...
    getString(message('MATLAB:timeseries:tsguis:mergedlg:UnionOfTimeVectorsOnTheIntervalWhereTheyOverlap')), ...
    'Units',...
    'Characters','Parent',PNLInterval,'Position',[3.2 8.459 70 1.1535],...
    'Tag', 'RADIOunion', 'Value',1);
h.Handles.RADIOintersect = uicontrol('style','radiobutton','String',...
    getString(message('MATLAB:timeseries:tsguis:mergedlg:IntersectionOfTimeVectorsOnTheInterval')), ...
    'Units',...
    'Characters','Parent',PNLInterval,'Position',[3.2 6.0751 70 1.1535],...
    'Tag', 'RADIOintersect');
h.Handles.RADIOuniform = uicontrol('style','radiobutton','String',...
    getString(message('MATLAB:timeseries:tsguis:mergedlg:UniformTimeVectorWithTimeInterval')), ...
    'Units',...
    'Characters','Parent',PNLInterval,'Position',[3.2 3.6912 42.8 1.1535]);
h.Handles.RADIOtimeseries = uicontrol('style','radiobutton','String',...
    getString(message('MATLAB:timeseries:tsguis:mergedlg:UseTimeVectorFromTimeSeries')), ...
    'Units',...
    'Characters','Parent',PNLInterval,'Position',[3.2 1.3842 40.8 1.1535],...
    'Tag', 'RADIOtimeseries');
h.Handles.EDITinterval = uicontrol('style','edit','Units',...
    'Characters','Parent',PNLInterval,'Position',[46.2 3.3836  14.4 1.6149],'String','1',...
    'HorizontalAlignment','Left','BackgroundColor',[1 1 1],'Callback',...
    {@localRefresh h},'Tag','EDITinterval');
h.Handles.COMBunits = uicontrol('style','popupmenu','Units',...
    'Characters','Parent',PNLInterval,'Position',[62.6 3.3067 15 1.6918],'String',...
    get(findtype('TimeUnits'),'String'),'Value',6,...
    'Callback',{@localRefresh h});
if ~ismac
   set(h.Handles.COMBunits,'BackgroundColor',[1 1 1]);
end
h.Handles.COMBts = uicontrol('style','popupmenu','Units',...
    'Characters','Parent',PNLInterval,'Position',[46 0.9228 31.8 1.6918],...
    'String',{' '},'Value',1,'Callback',{@localRefresh h});
if ~ismac
   set(h.Handles.COMBts,'BackgroundColor',[1 1 1]);
end

% Build time panel
PNLnewTime = uipanel('Parent',h.Figure,'Units','Characters','Position', ...
    [2.2 3.6143 81.6 5.5368],'Title', ...
    getString(message('MATLAB:timeseries:tsguis:mergedlg:NewTimeVector')));
h.Handles.TXTstarttime = uicontrol('style','text','Units',...
    'Characters','Parent',PNLnewTime,'Position',[3 2.353 74.8 1.3073],...
    'String', ...
    getString(message('MATLAB:timeseries:tsguis:mergedlg:StartEnd')), ...
    'HorizontalAlignment','Left');
h.Handles.TXTendtime = uicontrol('style','text','Units',...
    'Characters','Parent',PNLnewTime,'Position',[3 0.3536 74.8 1.3073],...
    'String', ...
    getString(message('MATLAB:timeseries:tsguis:mergedlg:NumberOfSamples')), ...
    'HorizontalAlignment','Left');

% Make the figure background color match the uipanel color
set(h.Figure,'Color',get(PNLnewTime,'BackGroundColor'))

% Install listeners
h.generic_listeners


function localOK(~,~, h)

% OK button callback to merge and resample the data
set(h.Figure,'Pointer','watch')

try % Prevent unexpected command line errors
    if h.eval;
       h.Visible = 'off';
    end 
    set(h.Figure,'Pointer','arrow')
catch %#ok<CTCH>
    set(h.Figure,'Pointer','arrow')
end

function localClose(~,~,h)

set(h,'Visible','off')

function localDispatchhelp(~,~,h)

tsDispatchHelp('d_resample_data_plot','modal',h.Figure)

function localRefresh(~,~,h)

refresh(h)