function domainpnl(h,f)

% Copyright 2004-2012 The MathWorks, Inc.

%% Build time panel
if ~isempty(h.Plot) && ishandle(h.Plot) 
    xlim = h.Plot.AxesGrid.getxlim(1);
else % Default time limits - no timeplot yet
    xlim = [0 1];
end
h.Handles.PNLDomain = uibuttongroup('Parent',f,'Units','Pixels','Title', ...
    getString(message('MATLAB:timeseries:tsguis:tshistnode:DefineHistogramBins')), ...
    'SelectionChangeFcn',@(es,ed) updatebins(h));

%% Build domain panel components
h.Handles.RADIOuniform = uicontrol('Style','Radiobutton','HorizontalAlignment','Left',...
    'Parent',h.Handles.PNLDomain,'String', ...
    getString(message('MATLAB:timeseries:tsguis:tshistnode:UniformCenters')), ...
    'Units','Pixels', ...
    'Position',[15 52 113 15],'Value',1);
LBLNumBins = uicontrol('Style','Text','String', ...
    getString(message('MATLAB:timeseries:tsguis:tshistnode:NumberOfBins')), ...
    'HorizontalAlignment',...
    'Left','Parent',h.Handles.PNLDomain,'Units','Pixels','Position',[137 50 103 17]);
h.Handles.TXTNumBins = uicontrol('Style','Edit','Parent',h.Handles.PNLDomain,'Units','Pixels', ...
    'Position',[233 48 168 21],'String','50','Callback', ...
    @(es,ed) updatebins(h),'HorizontalAlignment','Left','BackgroundColor',[1 1 1]);
h.Handles.RADIOcustom = uicontrol('Style','Radiobutton','HorizontalAlignment','Left',...
    'Parent',h.Handles.PNLDomain,'String', ...
    getString(message('MATLAB:timeseries:tsguis:tshistnode:Custom')), ...
    'Units','Pixels', ...
    'Position',[15 17 113 15]);
LBLCenters = uicontrol('Style','Text','String', ...
    getString(message('MATLAB:timeseries:tsguis:tshistnode:VectorOfCenters')), ...
    'HorizontalAlignment',...
    'Left','Parent',h.Handles.PNLDomain,'Units','Pixels','Position',[137 16 90 17]);
h.Handles.TXTCenters = uicontrol('Style','Edit','Parent',h.Handles.PNLDomain,'Units','Pixels', ...
    'Position',[233 12 168 21],'String','1:10','Callback', ...
    @(es,ed) updatebins(h),'HorizontalAlignment','Left','BackgroundColor',[1 1 1]);
