function initializeTimePanel(h)
% INITIALIZETIMEPANEL initializes the 'Define Time Vector' panel

% Author: Rong Chen 
%  Copyright 1986-2012 The MathWorks, Inc.

% -------------------------------------------------------------------------
%% Build time panel
% -------------------------------------------------------------------------
h.DefaultPos.TimePanelDefaultColor=h.DefaultPos.FigureDefaultColor;
if isfield(h.Handles,'PNLtime') && ishghandle(h.Handles.PNLtime)
    delete(h.Handles.PNLtime);
end
h.Handles.PNLtime = uipanel('Parent',h.Figure,...
    'Units','Pixels',...
    'FontSize',9,...
    'FontWeight','bold', ...
    'BackgroundColor',h.DefaultPos.TimePanelDefaultColor,...
    'Title',[' ', getString(message('MATLAB:timeseries:tsguis:workspaceImportdlg:SpecifyTimeVector')), ' '],...
    'Position',[h.DefaultPos.leftoffsetpnl ...
                h.DefaultPos.bottomoffsetTimepnl ...
                h.DefaultPos.widthpnl ...
                h.DefaultPos.heightTimepnl] ...
    );

% create sheet combobox controls whose values are based on the rawdata
huicTXTtimeSheet = uicontextmenu('Parent',h.Figure);
h.Handles.TXTtimeSheet = uicontrol('Parent',h.Handles.PNLtime,...
    'style','text', ...
    'Units','Pixels',...
    'BackgroundColor',h.DefaultPos.TimePanelDefaultColor,...
    'String',getString(message('MATLAB:timeseries:tsguis:workspaceImportdlg:TimeVectorSource')),...
    'HorizontalAlignment','Left', ...
    'UIContextMenu',huicTXTtimeSheet,...
    'Position',[h.DefaultPos.TXTtimeSheetleftoffset ...
                h.DefaultPos.TXTtimeSheetbottomoffset ...
                h.DefaultPos.TXTtimeSheetwidth ...
                h.DefaultPos.heighttxt] ...
    );
uimenu(huicTXTtimeSheet,'Label', ...
    getString(message('MATLAB:timeseries:tsguis:workspaceImportdlg:WhatsThis')), ...
    'Callback','tsDispatchHelp(''its_wiz_time_src_for_mat'',''modal'')')

h.Handles.COMBtimeSource = uicontrol('Parent',h.Handles.PNLtime,...
    'style','popupmenu',...
    'Units', 'Pixels',...
    'String',{getString(message('MATLAB:timeseries:tsguis:workspaceImportdlg:CurrentVariable')), ...
        getString(message('MATLAB:timeseries:tsguis:workspaceImportdlg:DefineItNow')), ...
        getString(message('MATLAB:timeseries:tsguis:workspaceImportdlg:AnotherVariable'))}, ...
    'Value',2,...
    'TooltipString', ...
        getString(message('MATLAB:timeseries:tsguis:workspaceImportdlg:TheTimeVectorCanBeObtained')),...
    'Position',[h.DefaultPos.COMBtimeSheetleftoffset ...
                h.DefaultPos.TXTtimeSheetbottomoffset+4 ...
                h.DefaultPos.COMBtimeSheetwidth ...
                h.DefaultPos.heightcomb], ...
    'Callback',{@localSwitchSource h}, ...
    'Tag', 'COMBtimeSource' ...
    );
if ~ismac
   set(h.Handles.COMBtimeSource,'BackgroundColor',[1 1 1]);
end

% create dynamic panels
h.dynamicPanel_CurrentSheet;
h.dynamicPanel_ManualInput;
h.dynamicPanel_Workspace;
% initialize dynamic panels
set(h.Handles.COMBdataSample,'Value',1);
h.TimePanelUpdate('column');
localSwitchSource(h.Handles.COMBtimeSource, [], h);


% -------------------------------------------------------------------------
%% time vector source selection callbacks
% -------------------------------------------------------------------------
function localSwitchSource(eventSrc, eventData, h)
% callback for the sheet combobox in the time panel
ind = get(eventSrc,'Value');
if ind==3
    % from workspace
    set(h.Handles.PNLtimeCurrentSheet,'Visible','off');
    set(h.Handles.PNLtimeManual,'Visible','off');
    set(h.Handles.PNLtimeWorkspace,'Visible','on');
elseif ind==2
    % manual input
    set(h.Handles.PNLtimeCurrentSheet,'Visible','off');
    set(h.Handles.PNLtimeManual,'Visible','on');
    set(h.Handles.PNLtimeWorkspace,'Visible','off');
elseif ind==1
    % currentsheet
    set(h.Handles.PNLtimeCurrentSheet,'Visible','on');
    set(h.Handles.PNLtimeManual,'Visible','off');
    set(h.Handles.PNLtimeWorkspace,'Visible','off');
end


