function TimePanelUpdate(h,option)
% TIMEPANELUPDATE updates the controls in time panel to the current display

% Author: Rong Chen 
%  Copyright 1986-2012 The MathWorks, Inc.

if strcmp(option,'column')
    % populate the index combo
    huicTXTtimeIndex = uicontextmenu('Parent',h.Figure);
    uimenu(huicTXTtimeIndex,'Label', ...
        getString(message('MATLAB:timeseries:tsguis:workspaceImportdlg:WhatsThis')), ...
        'Callback','tsDispatchHelp(''its_wiz_time_column_mat'',''modal'')')
    set(h.Handles.TXTtimeIndex, ...
        'String',getString(message('MATLAB:timeseries:tsguis:workspaceImportdlg:TimeIsInColumn')), ...
        'UIContextMenu',huicTXTtimeIndex);
    set(h.Handles.COMBtimeIndex,'String',h.GetColumn,'Value',1);
    % populate the unit/format combo
    if isfield(h.IOData.formatcell,'columnIsAbsTime') && h.IOData.formatcell.columnIsAbsTime>=0
        huicTXTtimeSheetFormat = uicontextmenu('Parent',h.Figure);
        uimenu(huicTXTtimeSheetFormat,'Label', ...
            getString(message('MATLAB:timeseries:tsguis:workspaceImportdlg:WhatsThis')), ...
            'Callback','tsDispatchHelp(''time_display_format'',''modal'')')
        set(h.Handles.TXTtimeSheetFormat, ...
            'String',getString(message('MATLAB:timeseries:tsguis:workspaceImportdlg:Format')), ...
            'UIContextMenu',huicTXTtimeSheetFormat);
        set(h.Handles.COMBtimeSheetFormat,'String',h.IOData.formatcell.matlabFormatString);    
        set(h.Handles.COMBtimeSheetFormat,'Value',find(h.IOData.formatcell.matlabFormatIndex == h.IOData.formatcell.columnIsAbsTime));
    else
        huicTXTtimeSheetFormat = uicontextmenu('Parent',h.Figure);
        uimenu(huicTXTtimeSheetFormat,'Label', ...
            getString(message('MATLAB:timeseries:tsguis:workspaceImportdlg:WhatsThis')), ...
            'Callback','tsDispatchHelp(''time_units_select'',''modal'')')
        set(h.Handles.TXTtimeSheetFormat, ...
            'String',getString(message('MATLAB:timeseries:tsguis:workspaceImportdlg:Units')), ...
            'UIContextMenu',huicTXTtimeSheetFormat);
        set(h.Handles.COMBtimeSheetFormat, ...
            'String',{getString(message('MATLAB:timeseries:tsguis:workspaceImportdlg:Weeks')), ...
            getString(message('MATLAB:timeseries:tsguis:workspaceImportdlg:Days')), ...
            getString(message('MATLAB:timeseries:tsguis:workspaceImportdlg:Hours')), ...
            getString(message('MATLAB:timeseries:tsguis:workspaceImportdlg:Minutes')), ...
            getString(message('MATLAB:timeseries:tsguis:workspaceImportdlg:Seconds')), ...
            getString(message('MATLAB:timeseries:tsguis:workspaceImportdlg:Milliseconds')), ...
            getString(message('MATLAB:timeseries:tsguis:workspaceImportdlg:Microseconds')), ...
            getString(message('MATLAB:timeseries:tsguis:workspaceImportdlg:Nanoseconds'))});    
        set(h.Handles.COMBtimeSheetFormat,'Value',5);
    end
else
    huicTXTtimeIndex = uicontextmenu('Parent',h.Figure);
    uimenu(huicTXTtimeIndex,'Label', ...
        getString(message('MATLAB:timeseries:tsguis:workspaceImportdlg:WhatsThis')), ...
        'Callback','tsDispatchHelp(''its_wiz_time_row_mat'',''modal'')')
    set(h.Handles.TXTtimeIndex, ...
        'String',getString(message('MATLAB:timeseries:tsguis:workspaceImportdlg:TimeIsInRow')), ...
        'UIContextMenu',huicTXTtimeIndex);
    set(h.Handles.COMBtimeIndex,'String',h.GetRow,'Value',1);
    % populate the unit/format combo
    if isfield(h.IOData.formatcell,'rowIsAbsTime') && h.IOData.formatcell.rowIsAbsTime>=0
        huicTXTtimeSheetFormat = uicontextmenu('Parent',h.Figure);
        uimenu(huicTXTtimeSheetFormat,'Label', ...
            getString(message('MATLAB:timeseries:tsguis:workspaceImportdlg:WhatsThis')), ...
            'Callback','tsDispatchHelp(''time_display_format'',''modal'')')
        set(h.Handles.TXTtimeSheetFormat, ...
            'String',getString(message('MATLAB:timeseries:tsguis:workspaceImportdlg:Format')), ...
            'UIContextMenu',huicTXTtimeSheetFormat);
        set(h.Handles.COMBtimeSheetFormat,'String',h.IOData.formatcell.matlabFormatString);    
        set(h.Handles.COMBtimeSheetFormat,'Value',find(h.IOData.formatcell.matlabFormatIndex == h.IOData.formatcell.rowIsAbsTime));
    else
        % populate the unit/format combo
        huicTXTtimeSheetFormat = uicontextmenu('Parent',h.Figure);
        uimenu(huicTXTtimeSheetFormat,'Label', ...
            getString(message('MATLAB:timeseries:tsguis:workspaceImportdlg:WhatsThis')), ...
            'Callback','tsDispatchHelp(''time_units_select'',''modal'')')
        set(h.Handles.TXTtimeSheetFormat, ...
            'String',getString(message('MATLAB:timeseries:tsguis:workspaceImportdlg:Units')), ...
            'UIContextMenu',huicTXTtimeSheetFormat);
        set(h.Handles.COMBtimeSheetFormat, ...
            'String',{getString(message('MATLAB:timeseries:tsguis:workspaceImportdlg:Weeks')), ...
            getString(message('MATLAB:timeseries:tsguis:workspaceImportdlg:Days')), ...
            getString(message('MATLAB:timeseries:tsguis:workspaceImportdlg:Hours')), ...
            getString(message('MATLAB:timeseries:tsguis:workspaceImportdlg:Minutes')), ...
            getString(message('MATLAB:timeseries:tsguis:workspaceImportdlg:Seconds')), ...
            getString(message('MATLAB:timeseries:tsguis:workspaceImportdlg:Milliseconds')), ...
            getString(message('MATLAB:timeseries:tsguis:workspaceImportdlg:Microseconds')), ...
            getString(message('MATLAB:timeseries:tsguis:workspaceImportdlg:Nanoseconds'))});    
        set(h.Handles.COMBtimeSheetFormat,'Value',5);
    end
end