function edit(view,h)

% Copyright 2004-2011 The MathWorks, Inc.

%% Listeners which keep the panels updated. These are @viewplot
%% specific
% h.Listeners = [h.Listeners;...
%      handle.listener(view.AxesGrid,'Viewchanged',@(es,ed) axespanel(h,view,'Y')); ...
%      handle.listener(view.AxesGrid,'Viewchanged',@(es,ed) updatechartable(view,h)); ...
%      handle.listener(view.AxesGrid,view.AxesGrid.findprop('XUnits'),'PropertyPreSet',...
%                    {@localUpdateCharUnits view h})];

h.Listeners = handle.listener(view.AxesGrid,view.AxesGrid.findprop('XUnits'),'PropertyPreSet',...
                   {@localUpdateCharUnits view h});

%% Build the @ploteditor
h.initialize(view)

%% Add panels
h.axespanel(view,'Y', ...
    getString(message('MATLAB:timeseries:tsguis:specplot:UseALogScaleForPeriodogramYValues'))); 
s = struct('charlist', ...
    {{getString(message('MATLAB:timeseries:tsguis:specplot:Variance')), ...
    'tsguis.tsCharVarData','tsguis.tsCharVarView'}},...
    'additionalDataProps',{{'StartFreq','EndFreq'}},'additionalDataPropDefaults',...
    {{'0','0.5'}},'additionalHeadings', ...
    {{getString(message('MATLAB:timeseries:tsguis:specplot:LowLimit')), ...
    getString(message('MATLAB:timeseries:tsguis:specplot:HighLimit'))}});
h.charpanel(view,s);
view.freqpnl(h);

function localUpdateCharUnits(es,ed,h,thispropedit)

%% Callback for changes in the plot time units which will update the
%% Start and End Times on the @timeplot char panel
drawnow
timeunitconv = tsunitconv(sprintf('%ss',ed.NewValue(5:end)),...
    sprintf('%ss',h.AxesGrid.XUnits(5:end)));
updatechartable(h,thispropedit,1/timeunitconv)

