function updatestats(h)

% Copyright 2004-2012 The MathWorks, Inc.

tsdata = h.Timeseries.Data;
tableData =  cell(size(tsdata,2),6);
for k=1:size(tableData,1)
    I = find(~isnan(tsdata(:,k)));
    if ~isempty(I)
        tableData(k,:) = {sprintf('%d',k),num2str(mean(tsdata(I,k))), ...
            num2str(median(tsdata(I,k))),...
            num2str(std(tsdata(I,k))),...
            num2str(min(tsdata(I,k))),...
            num2str(max(tsdata(I,k)))};
    else
        tableData(k,:) = {sprintf('%d',k),'','','','',''};
    end
end
h.Handles.statsTable.getModel.setDataVector(tableData,...
    {getString(message('MATLAB:timeseries:tsguis:statsdlg:ColumnNumber')), ...
    getString(message('MATLAB:timeseries:tsguis:statsdlg:Mean')), ...
    getString(message('MATLAB:timeseries:tsguis:statsdlg:Median')), ...
    getString(message('MATLAB:timeseries:tsguis:statsdlg:STD')), ...
    getString(message('MATLAB:timeseries:tsguis:statsdlg:Min')), ...
    getString(message('MATLAB:timeseries:tsguis:statsdlg:Max'))},...
    h.Handles.statsTable);