function clsList = matlabBuiltinClasses
    clsList =  { ...
        'cell';'char';'double';'int8';'int16';'int32';'int64'; ...
        'logical';'opaque';'single';'struct'; 'uint8';'uint16'; ...
        'uint32';'uint64';'handle' ...
    };
end
