function wb = createPreview(h,ts,wb)

% Copyright 2006-2012 The MathWorks, Inc.

%% Create a preview of the plot for early viewing...
wb = waitbar(0, ...
    getString(message('MATLAB:timeseries:tsguis:viewnode:InitializingTimeSeriesPlot')), ...
    'Name',...
    getString(message('MATLAB:timeseries:tsguis:viewnode:TimeSeriesTools')));
