function dynamicPanel_ManualInput(h)
% DYNAMICPANEL_MANUALINPUT initializes dynamic panel

% Author: Rong Chen 
%  Copyright 1986-2012 The MathWorks, Inc.

h.Handles.PNLtimeManual = uipanel('Parent',h.Handles.PNLtime,...
    'Units','Pixels',...
    'BackgroundColor',h.DefaultPos.TimePanelDefaultColor,...
    'BorderType','none',...
    'Position',[5 ...
                5 ...
                h.DefaultPos.widthpnl-10 ...
                h.DefaultPos.TXTtimeSheetbottomoffset-h.DefaultPos.separation-5], ...
    'Visible','off' ...                
    );

% Use: Numeric Time/Datastr edit box combo combination
huicTXTuseFormat = uicontextmenu('Parent',h.Figure);
strUse = getString(message('MATLAB:tsguis:excelImportdlg:dynamicPanel_ManualInput:Use'));
h.Handles.TXTuseFormat = uicontrol('Parent',h.Handles.PNLtimeManual,...
    'style','text', ...
    'Units','Pixels',...
    'BackgroundColor',h.DefaultPos.TimePanelDefaultColor,...
    'HorizontalAlignment','Left', ...
    'String',sprintf('%s : ',strUse), ...
    'UIContextMenu',huicTXTuseFormat,...
    'Position',[h.DefaultPos.TXTtimeIndexleftoffset ...
                h.DefaultPos.TXTtimeIndexbottomoffset ...
                h.DefaultPos.TXTtimeIndexwidth ...
                h.DefaultPos.heighttxt] ...
    );

strWhatsThisLabel = getString(message('MATLAB:tsguis:excelImportdlg:dynamicPanel_ManualInput:WhatsThisLabel'));
uimenu(huicTXTuseFormat,'Label',strWhatsThisLabel,'Callback','tsDispatchHelp(''its_use_time_format'',''modal'')')

h.Handles.COMBuseFormat = uicontrol('Parent',h.Handles.PNLtimeManual,...
    'style','popupmenu',...
    'Units', 'Pixels',...
    'String',[{getString(message('MATLAB:tsguis:excelImportdlg:dynamicPanel_ManualInput:DateString'))};{getString(message('MATLAB:tsguis:excelImportdlg:dynamicPanel_ManualInput:NumericalTime'))}], ...
    'Value',2, ...
    'Position',[h.DefaultPos.COMBtimeIndexleftoffset ...
                h.DefaultPos.TXTtimeIndexbottomoffset+4 ...
                h.DefaultPos.COMBtimeIndexwidth ...
                h.DefaultPos.heightcomb], ...
    'Callback',{@localSwitchUse h} ...
    );
if ~ismac
    set(h.Handles.COMBuseFormat,'BackgroundColor',[1 1 1]);
end

% Units edit box combo combination
huicTXTuseUnitFormat = uicontextmenu('Parent',h.Figure);
strUnits = getString(message('MATLAB:tsguis:excelImportdlg:dynamicPanel_ManualInput:Units'));
h.Handles.TXTtimeManualFormat = uicontrol('Parent',h.Handles.PNLtimeManual,...
    'style','text', ...
    'Units','Pixels',...
    'BackgroundColor',h.DefaultPos.TimePanelDefaultColor,...
    'HorizontalAlignment','Left', ...
    'String',sprintf('%s : ',strUnits), ...
    'UIContextMenu',huicTXTuseUnitFormat,...    
    'Position',[h.DefaultPos.TXTtimeSheetFormatleftoffset ...
                h.DefaultPos.TXTtimeSheetFormatbottomoffset ...
                h.DefaultPos.TXTtimeSheetFormatwidth ...
                h.DefaultPos.heighttxt] ...
    );
uimenu(huicTXTuseUnitFormat,'Label',strWhatsThisLabel,'Callback','tsDispatchHelp(''time_units_select'',''modal'')')
h.Handles.COMBtimeManualFormat = uicontrol('Parent',h.Handles.PNLtimeManual,...
    'style','popupmenu',...
    'Units', 'Pixels',...
    'String',{getString(message('MATLAB:tsguis:excelImportdlg:dynamicPanel_ManualInput:Weeks')), ...
        getString(message('MATLAB:tsguis:excelImportdlg:dynamicPanel_ManualInput:Days')), ...
        getString(message('MATLAB:tsguis:excelImportdlg:dynamicPanel_ManualInput:Hours')), ...
        getString(message('MATLAB:tsguis:excelImportdlg:dynamicPanel_ManualInput:Minutes')), ...
        getString(message('MATLAB:tsguis:excelImportdlg:dynamicPanel_ManualInput:Seconds')), ...
        getString(message('MATLAB:tsguis:excelImportdlg:dynamicPanel_ManualInput:Milliseconds')), ...
        getString(message('MATLAB:tsguis:excelImportdlg:dynamicPanel_ManualInput:Microseconds')), ...
        getString(message('MATLAB:tsguis:excelImportdlg:dynamicPanel_ManualInput:Nanoseconds'))}, ...
    'Value',5, ...
    'Position',[h.DefaultPos.COMBtimeSheetFormatleftoffset ...
                h.DefaultPos.TXTtimeSheetFormatbottomoffset+4 ...
                h.DefaultPos.COMBtimeSheetFormatwidth ...
                h.DefaultPos.heightcomb], ...
    'Callback',{@localSwitchFormat h} ...
    );
if ~ismac
    set(h.Handles.COMBtimeManualFormat,'BackgroundColor',[1 1 1]);
end


% Start time edit box, combo combination
huicTXTtimeManualStart = uicontextmenu('Parent',h.Figure);
strStartTime = getString(message('MATLAB:tsguis:excelImportdlg:dynamicPanel_ManualInput:StartTime'));
h.Handles.TXTtimeManualStart = uicontrol('Parent',h.Handles.PNLtimeManual,...
    'style','text', ...
    'Units','Pixels',...
    'BackgroundColor',h.DefaultPos.TimePanelDefaultColor,...
    'String',sprintf('%s : ',strStartTime),...
    'HorizontalAlignment','Left', ...
    'UIContextMenu',huicTXTtimeManualStart,...
    'Position',[h.DefaultPos.TXTtimeSheetStartleftoffset ...
                h.DefaultPos.TXTtimeSheetStartbottomoffset ...
                h.DefaultPos.TXTtimeSheetStartwidth ...
                h.DefaultPos.heighttxt] ...
    );
uimenu(huicTXTtimeManualStart,'Label',strWhatsThisLabel,'Callback','tsDispatchHelp(''start_time_enter'',''modal'')')
h.Handles.EDTtimeManualStart = uicontrol('Parent',h.Handles.PNLtimeManual,...
    'style','edit', ...
    'Units','Pixels',...
    'BackgroundColor',[1 1 1],...
    'String',' ',...
    'HorizontalAlignment','Left',...
    'Position',[h.DefaultPos.EDTtimeSheetStartleftoffset ...
                h.DefaultPos.TXTtimeSheetStartbottomoffset+2 ...
                h.DefaultPos.EDTtimeSheetStartwidth ...
                h.DefaultPos.heightedt], ...
    'Callback',{@localSetStartTime h}, ...
    'Tag', 'EDTtimeManualStart' ...
    );

% Samples edit box, combo combination
huicTXTtimeManualEnd = uicontextmenu('Parent',h.Figure);
strSamples = getString(message('MATLAB:tsguis:excelImportdlg:dynamicPanel_ManualInput:Samples'));
h.Handles.TXTtimeManualEnd = uicontrol('Parent',h.Handles.PNLtimeManual,...
    'style','text', ...
    'Units','Pixels',...
    'BackgroundColor',h.DefaultPos.TimePanelDefaultColor,...
    'String',sprintf('%s : ',strSamples),...
    'HorizontalAlignment','Left', ...
    'UIContextMenu',huicTXTtimeManualEnd,...
    'Position',[h.DefaultPos.TXTtimeSheetEndleftoffset ...
                h.DefaultPos.TXTtimeSheetEndbottomoffset ...
                h.DefaultPos.TXTtimeSheetEndwidth ...
                h.DefaultPos.heighttxt] ...
    );
uimenu(huicTXTtimeManualEnd,'Label',strWhatsThisLabel,'Callback','tsDispatchHelp(''number_samples_readonly'',''modal'')')

h.Handles.EDTtimeManualEnd = uicontrol('Parent',h.Handles.PNLtimeManual,...
    'style','edit', ...
    'Units','Pixels',...
    'BackgroundColor',[1 1 1],...
    'String',' ',...
    'HorizontalAlignment','Left',...
    'Position',[h.DefaultPos.EDTtimeSheetEndleftoffset ...
                h.DefaultPos.TXTtimeSheetEndbottomoffset+2 ...
                h.DefaultPos.EDTtimeManualEndwidth ...
                h.DefaultPos.heightedt], ...
    'Enable','off' ...
    );

% Interval;
% edit box, combo combination
huicTXTtimeManualInterval = uicontextmenu('Parent',h.Figure);
strInterval = getString(message('MATLAB:tsguis:excelImportdlg:dynamicPanel_ManualInput:Interval'));
h.Handles.TXTtimeManualInterval = uicontrol('Parent',h.Handles.PNLtimeManual,...
    'style','text', ...
    'Units','Pixels',...
    'BackgroundColor',h.DefaultPos.TimePanelDefaultColor,...
    'String',sprintf('%s : ',strInterval),...
    'HorizontalAlignment','Right', ...
    'UIContextMenu',huicTXTtimeManualInterval,...
    'Position',[h.DefaultPos.TXTtimeManualIntervalleftoffset ...
                h.DefaultPos.TXTtimeSheetIntervalbottomoffset ...
                h.DefaultPos.TXTtimeManualIntervalwidth ...
                h.DefaultPos.heighttxt] ...        
    );
uimenu(huicTXTtimeManualInterval,'Label',strWhatsThisLabel,'Callback','tsDispatchHelp(''time_interval'',''modal'')')

h.Handles.EDTtimeManualInterval = uicontrol('Parent',h.Handles.PNLtimeManual,...
    'style','edit', ...
    'Units','Pixels',...
    'BackgroundColor',[1 1 1],...
    'String',' ',...
    'HorizontalAlignment','Left',...
    'Position',[h.DefaultPos.EDTtimeManualIntervalleftoffset ...
                h.DefaultPos.TXTtimeSheetIntervalbottomoffset+2 ...
                h.DefaultPos.EDTtimeSheetIntervalwidth ...
                h.DefaultPos.heightedt], ...
    'Callback',{@localSetInterval h}, ...
    'Tag', 'EDTtimeManualInterval' ...    
    );

h.Handles.TXTtimeManualIntervalUnit = uicontrol('Parent',h.Handles.PNLtimeManual,...
    'style','text', ...
    'Units','Pixels',...
    'BackgroundColor',h.DefaultPos.TimePanelDefaultColor,...
    'String','seconds',...
    'HorizontalAlignment','Left', ...
    'Position',[h.DefaultPos.UNITtimeSheetIntervalleftoffset ...
                h.DefaultPos.TXTtimeSheetIntervalbottomoffset ...
                h.DefaultPos.UNITtimeSheetIntervalwidth ...
                h.DefaultPos.heighttxt], ...
    'Visible','off' ...                                
    );


function localSwitchUse(eventSrc, eventData, h)
%% Callback for the absolute/relative time format combo

if get(h.Handles.COMBuseFormat,'Value')==1
    % Set the contents of the format combo to be absolute time formats
    strFormat = getString(message('MATLAB:tsguis:excelImportdlg:dynamicPanel_ManualInput:Format'));
    set(h.Handles.TXTtimeManualFormat,'String',sprintf('%s : ',strFormat))
    huicTXTuseUnitFormat = uicontextmenu('Parent',h.Figure);
    set(h.Handles.TXTtimeManualFormat,'UIContextMenu',huicTXTuseUnitFormat);
    uimenu(huicTXTuseUnitFormat,'Label',getString(message('MATLAB:tsguis:excelImportdlg:dynamicPanel_ManualInput:WhatsThisLabel')),'Callback','tsDispatchHelp(''time_display_format'',''modal'')')
    
    set(h.Handles.COMBtimeManualFormat,'String',h.IOData.formatcell.matlabFormatString,'Value',1)
    % display the content in relative time formats
    set(h.Handles.EDTtimeManualStart,'String',datestr(now));
    set(h.Handles.EDTtimeManualInterval,'String','1');
    % switch unit text on
    set(h.Handles.TXTtimeManualIntervalUnit,'Visible','on');
else
    % Set the contents of the format combo to be relative time formats
    strUnits = getString(message('MATLAB:tsguis:excelImportdlg:dynamicPanel_ManualInput:Units'));
    set(h.Handles.TXTtimeManualFormat,'String',sprintf('%s : ',strUnits))
    huicTXTuseUnitFormat = uicontextmenu('Parent',h.Figure);
    set(h.Handles.TXTtimeManualFormat,'UIContextMenu',huicTXTuseUnitFormat);
    uimenu(huicTXTuseUnitFormat,'Label',getString(message('MATLAB:tsguis:excelImportdlg:dynamicPanel_ManualInput:WhatsThisLabel')),'Callback','tsDispatchHelp(''time_units_select'',''modal'')')

    set(h.Handles.COMBtimeManualFormat,'String',{getString(message('MATLAB:tsguis:excelImportdlg:dynamicPanel_ManualInput:Weeks')), ...
        getString(message('MATLAB:tsguis:excelImportdlg:dynamicPanel_ManualInput:Days')), ...
        getString(message('MATLAB:tsguis:excelImportdlg:dynamicPanel_ManualInput:Hours')), ...
        getString(message('MATLAB:tsguis:excelImportdlg:dynamicPanel_ManualInput:Minutes')), ...
        getString(message('MATLAB:tsguis:excelImportdlg:dynamicPanel_ManualInput:Seconds')), ...
        getString(message('MATLAB:tsguis:excelImportdlg:dynamicPanel_ManualInput:Milliseconds')), ...
        getString(message('MATLAB:tsguis:excelImportdlg:dynamicPanel_ManualInput:Microseconds')), ...
        getString(message('MATLAB:tsguis:excelImportdlg:dynamicPanel_ManualInput:Nanoseconds'))},'Value',5);
    % display the content in relative time formats
    set(h.Handles.EDTtimeManualStart,'String','0');
    set(h.Handles.EDTtimeManualInterval,'String','1');
    % switch unit text off
    set(h.Handles.TXTtimeManualIntervalUnit,'Visible','off');
end


function localSetStartTime(eventSrc, eventData, h)
%% Callback for the start time edit box


function localSetInterval(eventSrc, eventData, h)
%% Callback for the interval time edit box


function localSwitchFormat(eventSrc, eventData, h)
%% Callback for the format/unit edit box
switch h.IOData.formatcell.matlabFormatIndex(get(h.Handles.COMBtimeManualFormat,'Value'))
    case {0 13 14 21} 
        %'dd-mmm-yyyy HH:MM:SS' 'HH:MM:SS' 'HH:MM:SS PM' 'mmm.dd,yyyy HH:MM:SS'
        set(h.Handles.TXTtimeManualIntervalUnit,'String','seconds');
    case {1 2 6 22 23}
        set(h.Handles.TXTtimeManualIntervalUnit,'String','days');
    case {15 16}
        set(h.Handles.TXTtimeManualIntervalUnit,'String','minutes');        
end


